import { getMovie } from "@/lib/getMovie";
import { Suspense } from "react";
import { OriginalMovie } from "../../components/original";

export async function generateMetadata({ params }): Promise<Metadata> {
  const movieData = await getMovie(params.id);
  if (movieData.remake)
    return {
      title: `${movieData.original_title} AI generated reamke`,
      desciption: `Reamke of the clasic movie ${movieData.orginal_title} generated by chatGPT - Hollywood Movie Remake Generator`,
      images: [
        {
          url: movieData.remake.imageURL,
          width: 512,
          height: 412,
        },

      ],
      locale: 'en-US',
      type: 'website',
    };
}

export default async function Page({ params }: { params: { id: string } }) {
  const movieData = await getMovie(params.id);
  return (
    <Suspense fallback={<></>}>
      {/* @ts-expect-error Async Server Component */}
      <OriginalMovie promise={movieData} />
    </Suspense>
  );
}
