import "../../globals.css";
import { Abril_Fatface } from "next/font/google";
import styles from "../../styles.module.css";
const abril_fatface = Abril_Fatface({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "Movie Remake Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <h1 className={`${styles.headline} ${abril_fatface.className}`}>
        Hollywood Movie Remake Generator
      </h1>

      {children}
    </>
  );
}
