import "./globals.css";
import { MovieSearchForm } from "./components/search";
import { Abril_Fatface } from "next/font/google";
import styles from "./styles.module.css";
const abril_fatface = Abril_Fatface({ weight: ["400"], subsets: ["latin"] });

export const metadata = {
  title: "Movie Remake Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className={styles.main}>
          <div>{children}</div>
        </main>
      </body>
    </html>
  );
}
