version = 0.1
[default.deploy.parameters]
stack_name = "lambda-streaming-movie-remake"
resolve_s3 = true
s3_prefix = "lambda-streaming-movie-remake"
region = "eu-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
